# Generated by Django 5.2.4 on 2025-11-26 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        ('submit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codesubmission',
            options={'verbose_name': 'Legacy Code Submission'},
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('py', 'Python'), ('cpp', 'C++'), ('c', 'C'), ('java', 'Java')], max_length=10)),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('tle', 'Time Limit Exceeded'), ('rte', 'Runtime Error'), ('ce', 'Compilation Error'), ('mle', 'Memory Limit Exceeded')], default='pending', max_length=20)),
                ('runtime_ms', models.IntegerField(blank=True, null=True)),
                ('memory_kb', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('tests_passed', models.PositiveIntegerField(default=0)),
                ('tests_total', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('judged_at', models.DateTimeField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('tle', 'Time Limit Exceeded'), ('rte', 'Runtime Error'), ('ce', 'Compilation Error'), ('mle', 'Memory Limit Exceeded')], max_length=20)),
                ('actual_output', models.TextField(blank=True)),
                ('runtime_ms', models.IntegerField(blank=True, null=True)),
                ('memory_kb', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='submit.submission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.testcase')),
            ],
            options={
                'ordering': ['test_case__order'],
            },
        ),
    ]
